# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ps_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ps_service.proto',
  package='ps_service',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10ps_service.proto\x12\nps_service\x1a\x1bgoogle/protobuf/empty.proto\"j\n\x04Grad\x12\n\n\x02id\x18\x01 \x02(\t\x12\x15\n\rlearning_rate\x18\x02 \x02(\x01\x12\x0e\n\x06length\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x01\x12\x0e\n\x06n_iter\x18\x05 \x02(\x05\x12\x11\n\tworker_id\x18\x06 \x02(\x05\"U\n\x06Update\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x01\x12\x0e\n\x06n_iter\x18\x04 \x02(\x05\x12\x11\n\tworker_id\x18\x05 \x02(\x05\"1\n\x05Model\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x01\"B\n\x0fRegisterRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0e\n\x06length\x18\x02 \x02(\x05\x12\x13\n\x0bparallelism\x18\x03 \x02(\x05\"\x1a\n\x0c\x45xistRequest\x12\n\n\x02id\x18\x01 \x02(\t\">\n\rWorkerRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0e\n\x06n_iter\x18\x02 \x02(\x05\x12\x11\n\tworker_id\x18\x03 \x02(\x05\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x02(\x08\x32\xf1\x03\n\x0fParameterServer\x12\x34\n\x04ping\x12\x16.google.protobuf.Empty\x1a\x12.ps_service.Status\"\x00\x12\x43\n\x0eregister_model\x12\x1b.ps_service.RegisterRequest\x1a\x12.ps_service.Status\"\x00\x12=\n\x0b\x65xist_model\x12\x18.ps_service.ExistRequest\x1a\x12.ps_service.Status\"\x00\x12;\n\x08\x63\x61n_pull\x12\x19.ps_service.WorkerRequest\x1a\x12.ps_service.Status\"\x00\x12;\n\x08\x63\x61n_push\x12\x19.ps_service.WorkerRequest\x1a\x12.ps_service.Status\"\x00\x12<\n\npull_model\x12\x19.ps_service.WorkerRequest\x1a\x11.ps_service.Model\"\x00\x12\x33\n\tpush_grad\x12\x10.ps_service.Grad\x1a\x12.ps_service.Status\"\x00\x12\x37\n\x0bpush_update\x12\x12.ps_service.Update\x1a\x12.ps_service.Status\"\x00'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_GRAD = _descriptor.Descriptor(
  name='Grad',
  full_name='ps_service.Grad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ps_service.Grad.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='ps_service.Grad.learning_rate', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='ps_service.Grad.length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ps_service.Grad.data', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_iter', full_name='ps_service.Grad.n_iter', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='ps_service.Grad.worker_id', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=167,
)


_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='ps_service.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ps_service.Update.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='ps_service.Update.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ps_service.Update.data', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_iter', full_name='ps_service.Update.n_iter', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='ps_service.Update.worker_id', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=254,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='ps_service.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ps_service.Model.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='ps_service.Model.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ps_service.Model.data', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=305,
)


_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='ps_service.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ps_service.RegisterRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='ps_service.RegisterRequest.length', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parallelism', full_name='ps_service.RegisterRequest.parallelism', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=373,
)


_EXISTREQUEST = _descriptor.Descriptor(
  name='ExistRequest',
  full_name='ps_service.ExistRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ps_service.ExistRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=401,
)


_WORKERREQUEST = _descriptor.Descriptor(
  name='WorkerRequest',
  full_name='ps_service.WorkerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ps_service.WorkerRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_iter', full_name='ps_service.WorkerRequest.n_iter', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='ps_service.WorkerRequest.worker_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=465,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='ps_service.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ps_service.Status.status', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=491,
)

DESCRIPTOR.message_types_by_name['Grad'] = _GRAD
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['ExistRequest'] = _EXISTREQUEST
DESCRIPTOR.message_types_by_name['WorkerRequest'] = _WORKERREQUEST
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Grad = _reflection.GeneratedProtocolMessageType('Grad', (_message.Message,), {
  'DESCRIPTOR' : _GRAD,
  '__module__' : 'ps_service_pb2'
  # @@protoc_insertion_point(class_scope:ps_service.Grad)
  })
_sym_db.RegisterMessage(Grad)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE,
  '__module__' : 'ps_service_pb2'
  # @@protoc_insertion_point(class_scope:ps_service.Update)
  })
_sym_db.RegisterMessage(Update)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'ps_service_pb2'
  # @@protoc_insertion_point(class_scope:ps_service.Model)
  })
_sym_db.RegisterMessage(Model)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'ps_service_pb2'
  # @@protoc_insertion_point(class_scope:ps_service.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

ExistRequest = _reflection.GeneratedProtocolMessageType('ExistRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXISTREQUEST,
  '__module__' : 'ps_service_pb2'
  # @@protoc_insertion_point(class_scope:ps_service.ExistRequest)
  })
_sym_db.RegisterMessage(ExistRequest)

WorkerRequest = _reflection.GeneratedProtocolMessageType('WorkerRequest', (_message.Message,), {
  'DESCRIPTOR' : _WORKERREQUEST,
  '__module__' : 'ps_service_pb2'
  # @@protoc_insertion_point(class_scope:ps_service.WorkerRequest)
  })
_sym_db.RegisterMessage(WorkerRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'ps_service_pb2'
  # @@protoc_insertion_point(class_scope:ps_service.Status)
  })
_sym_db.RegisterMessage(Status)



_PARAMETERSERVER = _descriptor.ServiceDescriptor(
  name='ParameterServer',
  full_name='ps_service.ParameterServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=494,
  serialized_end=991,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='ps_service.ParameterServer.ping',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='register_model',
    full_name='ps_service.ParameterServer.register_model',
    index=1,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='exist_model',
    full_name='ps_service.ParameterServer.exist_model',
    index=2,
    containing_service=None,
    input_type=_EXISTREQUEST,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='can_pull',
    full_name='ps_service.ParameterServer.can_pull',
    index=3,
    containing_service=None,
    input_type=_WORKERREQUEST,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='can_push',
    full_name='ps_service.ParameterServer.can_push',
    index=4,
    containing_service=None,
    input_type=_WORKERREQUEST,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='pull_model',
    full_name='ps_service.ParameterServer.pull_model',
    index=5,
    containing_service=None,
    input_type=_WORKERREQUEST,
    output_type=_MODEL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='push_grad',
    full_name='ps_service.ParameterServer.push_grad',
    index=6,
    containing_service=None,
    input_type=_GRAD,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='push_update',
    full_name='ps_service.ParameterServer.push_update',
    index=7,
    containing_service=None,
    input_type=_UPDATE,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARAMETERSERVER)

DESCRIPTOR.services_by_name['ParameterServer'] = _PARAMETERSERVER

# @@protoc_insertion_point(module_scope)
